name: Establish CI workflows
on: 
  pull_request:
    types: [opened, reopened , review_requested, synchronize]

jobs:
  setup-machine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Run Docker
        run: |
          export ANYSCALE_HOST: ${{ secrets.ANYSCALE_HOST }}
          export ANYSCALE_CLI_TOKEN: ${{ secrets.ANYSCALE_CLI_TOKEN }}
          anyscale image build -n churn-job-image --containerfile Dockerfile
